/* tslint:disable */
/* eslint-disable */
/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: https://docs.flyo.cloud/doc/integrations-nitro-cms
 *
 * The version of the OpenAPI document: 1.70.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityinterfaceInner,
} from '../models/index';
import {
    EntityinterfaceInnerFromJSON,
    EntityinterfaceInnerToJSON,
} from '../models/index';

export interface SearchRequest {
    query: string;
    sort?: SearchSortEnum;
    page?: number;
    lang?: string;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * This endpoint offers a powerful full-text search through the websites sitemap, encompassing both pages and entities. It performs word-based matching against entity titles and teasers. Each result includes a `score` field representing the relevance of the match. By default, results are sorted by relevance (highest score first). Each result also includes an `href` attribute containing the resolved URL path for the entity. In multi-lingual setups, search results are automatically filtered to match the current language context specified via the `lang` parameter, ensuring only results relevant to the requested language are returned.
     * Get Search by query
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EntityinterfaceInner>>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiToken authentication
        }


        let urlPath = `/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EntityinterfaceInnerFromJSON));
    }

    /**
     * This endpoint offers a powerful full-text search through the websites sitemap, encompassing both pages and entities. It performs word-based matching against entity titles and teasers. Each result includes a `score` field representing the relevance of the match. By default, results are sorted by relevance (highest score first). Each result also includes an `href` attribute containing the resolved URL path for the entity. In multi-lingual setups, search results are automatically filtered to match the current language context specified via the `lang` parameter, ensuring only results relevant to the requested language are returned.
     * Get Search by query
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EntityinterfaceInner>> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchSortEnum = {
    score: 'score',
    score2: '-score',
    title: 'title',
    title2: '-title',
    time_start: 'time_start',
    time_start2: '-time_start',
    updated_at: 'updated_at',
    updated_at2: '-updated_at'
} as const;
export type SearchSortEnum = typeof SearchSortEnum[keyof typeof SearchSortEnum];
