/* tslint:disable */
/* eslint-disable */
/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: https://docs.flyo.cloud/doc/integrations-nitro-cms
 *
 * The version of the OpenAPI document: 2.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SitemapinterfaceInner,
    SitemapinterfaceInnerFromJSON,
    SitemapinterfaceInnerToJSON,
} from '../models/SitemapinterfaceInner';

export interface SitemapRequest {
    lang?: string;
}

/**
 * 
 */
export class SitemapApi extends runtime.BaseAPI {

    /**
     * Creates request options for sitemap without sending the request
     */
    async sitemapRequestOpts(requestParameters: SitemapRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiToken authentication
        }


        let urlPath = `/sitemap`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint provides the data needed to generate a sitemap. It encompasses pages from containers as well as all entities that have been mapped. Each item includes an `href` attribute containing the resolved URL path, an `updated_at` Unix timestamp which should be used as the `lastmod` value of the sitemap entry, and the `entity_unique_id` to correlate the entry with its entity. Entities and pages without a resolvable URL are omitted. The response is deliberately reduced to those three fields (see the Sitemap Item schema) and is streamed as a bare JSON array without pagination; presentation fields such as title, teaser and image, and the `routes` map, are only available on the entities and search endpoints. In multi-lingual setups, the sitemap returns all language variants of every entity and page, regardless of the `lang` parameter. This ensures complete SEO coverage across all configured languages.
     * Get Sitemap
     */
    async sitemapRaw(requestParameters: SitemapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SitemapinterfaceInner>>> {
        const requestOptions = await this.sitemapRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SitemapinterfaceInnerFromJSON));
    }

    /**
     * This endpoint provides the data needed to generate a sitemap. It encompasses pages from containers as well as all entities that have been mapped. Each item includes an `href` attribute containing the resolved URL path, an `updated_at` Unix timestamp which should be used as the `lastmod` value of the sitemap entry, and the `entity_unique_id` to correlate the entry with its entity. Entities and pages without a resolvable URL are omitted. The response is deliberately reduced to those three fields (see the Sitemap Item schema) and is streamed as a bare JSON array without pagination; presentation fields such as title, teaser and image, and the `routes` map, are only available on the entities and search endpoints. In multi-lingual setups, the sitemap returns all language variants of every entity and page, regardless of the `lang` parameter. This ensures complete SEO coverage across all configured languages.
     * Get Sitemap
     */
    async sitemap(requestParameters: SitemapRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SitemapinterfaceInner>> {
        const response = await this.sitemapRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
