/* tslint:disable */
/* eslint-disable */
/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: https://docs.flyo.cloud/doc/integrations-nitro-cms
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Translation } from './Translation';
import {
    TranslationFromJSON,
    TranslationFromJSONTyped,
    TranslationToJSON,
    TranslationToJSONTyped,
} from './Translation';
import type { Breadcrumb } from './Breadcrumb';
import {
    BreadcrumbFromJSON,
    BreadcrumbFromJSONTyped,
    BreadcrumbToJSON,
    BreadcrumbToJSONTyped,
} from './Breadcrumb';
import type { EntityInterface } from './EntityInterface';
import {
    EntityInterfaceFromJSON,
    EntityInterfaceFromJSONTyped,
    EntityInterfaceToJSON,
    EntityInterfaceToJSONTyped,
} from './EntityInterface';

/**
 * 
 * @export
 * @interface Entity
 */
export interface Entity {
    /**
     * 
     * @type {EntityInterface}
     * @memberof Entity
     */
    entity?: EntityInterface;
    /**
     * All values which are mappend from inside flyo trough the mapping system are stored inside this object.
     * @type {object}
     * @memberof Entity
     */
    model?: object;
    /**
     * Current language context for entity model data
     * @type {string}
     * @memberof Entity
     */
    language?: string;
    /**
     * Whether this response was served from a **draft link** rather than from published content. Always present, and `false` for every regular request. A draft link is a shareable, expiring snapshot of an entity which is still offline in Flyo: because offline content is never delivered to an integration, this is the only way such an entity can be looked at on the website at all. The snapshot is addressed by a cryptic token which takes the place of the entity's unique id and slug, so a draft is requested through the very same endpoints as any other entity — `/entities/uniqueid/{uniqueid}` and `/entities/slug/{slug}` — with the token as the parameter. Use this flag to render a visible hint that the visitor is not looking at the live page. Note that the token does not look like a normal slug or unique id, so a router which validates those parameters against a pattern has to let it through for drafts to work.
     * @type {boolean}
     * @memberof Entity
     */
    is_draft?: boolean;
    /**
     * The Unix timestamp at which the draft link stops working, or `null` when `is_draft` is `false`. Every draft link expires; after that moment the same URL answers with a 404 like any unknown entity. Useful to tell a reviewer how long the link they were sent remains valid.
     * @type {number}
     * @memberof Entity
     */
    draft_expires_at?: number | null;
    /**
     * A Json LD based object with schema.org informations about the entity
     * @type {object}
     * @memberof Entity
     */
    jsonld?: object;
    /**
     * The translation contains information about further data in different languages. If the integration is not defined as multi lingual, the translations will be empty.
     * @type {Array<Translation>}
     * @memberof Entity
     */
    translation?: Array<Translation>;
    /**
     * The breadcrumb of the current site is represented by an array of pages, forming a navigational path. It provides a hierarchical representation of the user's current location within the website. The array is ordered from the innermost page, closest to the current page, to the outermost page, with the current page itself residing at the last position.
     * @type {Array<Breadcrumb>}
     * @memberof Entity
     */
    breadcrumb?: Array<Breadcrumb>;
    /**
     * The **canonical URL path** of this entity, ready to be rendered as `<link rel="canonical">`. A collection can be configured with several routes - a detail route, a print view, an embed - but exactly one of them is flagged as the *canonical route* in the entity mapping, and that route is the address the entity itself lives at. Its resolved path is what this field carries, and it is the very same value the sitemap and the search results carry, so a search engine is never offered two competing addresses for the same content. The path is relative to the site root and already resolved for the requested language, exactly like every other path in this API - prefix it with your own domain. Empty when the collection has no route configured at all: such an entity has no public address and must not emit a canonical tag. For a **draft link** it resolves with the draft token in place of the unique id and slug, so it points at the draft itself and not at the not yet published entity.
     * @type {string}
     * @memberof Entity
     */
    canonical?: string;
    /**
     * Whether this entity may be indexed by search engines. `false` when every page placing the entity's content pool is marked non-indexable and the pool is not an indexed pool: the entity is then absent from the sitemap and the search endpoint, and the consumer should render `<meta name="robots" content="noindex">` for the detail page. Not access control - the entity resolves by id and slug like any other. Always `false` for a draft link.
     * @type {boolean}
     * @memberof Entity
     */
    is_indexable?: boolean;
}

/**
 * Check if a given object implements the Entity interface.
 */
export function instanceOfEntity(value: object): value is Entity {
    return true;
}

export function EntityFromJSON(json: any): Entity {
    return EntityFromJSONTyped(json, false);
}

export function EntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entity {
    if (json == null) {
        return json;
    }
    return {
        
        'entity': json['entity'] == null ? undefined : EntityInterfaceFromJSON(json['entity']),
        'model': json['model'] == null ? undefined : json['model'],
        'language': json['language'] == null ? undefined : json['language'],
        'is_draft': json['is_draft'] == null ? undefined : json['is_draft'],
        'draft_expires_at': json['draft_expires_at'] === undefined ? undefined : json['draft_expires_at'] === null ? null : json['draft_expires_at'],
        'jsonld': json['jsonld'] == null ? undefined : json['jsonld'],
        'translation': json['translation'] == null ? undefined : ((json['translation'] as Array<any>).map(TranslationFromJSON)),
        'breadcrumb': json['breadcrumb'] == null ? undefined : ((json['breadcrumb'] as Array<any>).map(BreadcrumbFromJSON)),
        'canonical': json['canonical'] == null ? undefined : json['canonical'],
        'is_indexable': json['is_indexable'] == null ? undefined : json['is_indexable'],
    };
}

export function EntityToJSON(json: any): Entity {
    return EntityToJSONTyped(json, false);
}

export function EntityToJSONTyped(value?: Entity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity': EntityInterfaceToJSON(value['entity']),
        'model': value['model'],
        'language': value['language'],
        'is_draft': value['is_draft'],
        'draft_expires_at': value['draft_expires_at'],
        'jsonld': value['jsonld'],
        'translation': value['translation'] == null ? undefined : ((value['translation'] as Array<any>).map(TranslationToJSON)),
        'breadcrumb': value['breadcrumb'] == null ? undefined : ((value['breadcrumb'] as Array<any>).map(BreadcrumbToJSON)),
        'canonical': value['canonical'],
        'is_indexable': value['is_indexable'],
    };
}

