/* tslint:disable */
/* eslint-disable */
/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: dev.flyo.cloud
 *
 * The version of the OpenAPI document: 1.0.0-beta.197
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldLink
 */
export interface FieldLink {
    /**
     * The type of the link. Possible values are: nitropagelink, url, email, tel, file
     * @type {string}
     * @memberof FieldLink
     */
    type?: string;
    /**
     * The target attribute of the link. Possible values are: _blank, _self
     * @type {string}
     * @memberof FieldLink
     */
    target?: string;
    /**
     * The not modified raw input value of flyo.
     * @type {string}
     * @memberof FieldLink
     */
    raw?: string;
    /**
     * The link in a href format. Which means links have a trailing slash. E-Mail links start with mailto: and phone links start with tel:
     * @type {string}
     * @memberof FieldLink
     */
    href?: string;
    /**
     * Additional information about the link. This information can vary depending on the type of link.
     * @type {object}
     * @memberof FieldLink
     */
    extras?: object;
}

/**
 * Check if a given object implements the FieldLink interface.
 */
export function instanceOfFieldLink(value: object): boolean {
    return true;
}

export function FieldLinkFromJSON(json: any): FieldLink {
    return FieldLinkFromJSONTyped(json, false);
}

export function FieldLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldLink {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'target': json['target'] == null ? undefined : json['target'],
        'raw': json['raw'] == null ? undefined : json['raw'],
        'href': json['href'] == null ? undefined : json['href'],
        'extras': json['extras'] == null ? undefined : json['extras'],
    };
}

export function FieldLinkToJSON(value?: FieldLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'target': value['target'],
        'raw': value['raw'],
        'href': value['href'],
        'extras': value['extras'],
    };
}

