/* tslint:disable */
/* eslint-disable */
/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: https://docs.flyo.cloud/doc/integrations-nitro-cms
 *
 * The version of the OpenAPI document: 2.28
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Map of resolved route identifiers to URL paths, for example `routes.detail = "/foo-bar"`. Includes the system key `_empty` (boolean): `false` means at least one route could be resolved, `true` means no route is available for the current context.
 * @export
 * @interface Routes
 */
export interface Routes {
    [key: string]: string | any;
    /**
     * Whether no route could be resolved (`true` when the map has no routes).
     * @type {boolean}
     * @memberof Routes
     */
    _empty?: boolean;
}

/**
 * Check if a given object implements the Routes interface.
 */
export function instanceOfRoutes(value: object): value is Routes {
    return true;
}

export function RoutesFromJSON(json: any): Routes {
    return RoutesFromJSONTyped(json, false);
}

export function RoutesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Routes {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '_empty': json['_empty'] == null ? undefined : json['_empty'],
    };
}

export function RoutesToJSON(json: any): Routes {
    return RoutesToJSONTyped(json, false);
}

export function RoutesToJSONTyped(value?: Routes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        '_empty': value['_empty'],
    };
}

