/* tslint:disable */
/* eslint-disable */
/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: https://docs.flyo.cloud/doc/integrations-nitro-cms
 *
 * The version of the OpenAPI document: 2.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitemapinterfaceInner
 */
export interface SitemapinterfaceInner {
    /**
     * Unique ID
     * @type {string}
     * @memberof SitemapinterfaceInner
     */
    entity_unique_id?: string;
    /**
     * A Unix timestamp indicating when the entity has been updated last time in Flyo. For entries which represent a Nitro page, this is the last time the content delivered for that page actually changed — a rebuild which produces identical output does not move it. Use this value as the `lastmod` information when generating a sitemap.
     * @type {number}
     * @memberof SitemapinterfaceInner
     */
    updated_at?: number;
    /**
     * Returns the completed href tag. Internal links are appended with trailing slashes, such as `/about-me`, while email links are formatted with `mailto:hello@flyo.ch`.
     * @type {string}
     * @memberof SitemapinterfaceInner
     */
    href?: string;
    /**
     * Deprecated — read `href` instead, which is already resolved for both pages (`nitro-page`) and mapped entities. Only kept for consumers that branch on the type to decide how to build the URL themselves.
     * @type {string}
     * @memberof SitemapinterfaceInner
     * @deprecated
     */
    entity_type?: string;
    /**
     * Deprecated — read `href` instead. Only kept for consumers that build a container page URL from its slug.
     * @type {string}
     * @memberof SitemapinterfaceInner
     * @deprecated
     */
    entity_slug?: string;
    /**
     * Deprecated — read `href` instead, which holds the first resolved route. Only kept for consumers that pick a specific route identifier such as `routes.detail`. Includes the system key `_empty` (boolean): `false` means at least one route could be resolved.
     * @type {{ [key: string]: any; }}
     * @memberof SitemapinterfaceInner
     * @deprecated
     */
    routes?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SitemapinterfaceInner interface.
 */
export function instanceOfSitemapinterfaceInner(value: object): value is SitemapinterfaceInner {
    return true;
}

export function SitemapinterfaceInnerFromJSON(json: any): SitemapinterfaceInner {
    return SitemapinterfaceInnerFromJSONTyped(json, false);
}

export function SitemapinterfaceInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitemapinterfaceInner {
    if (json == null) {
        return json;
    }
    return {
        
        'entity_unique_id': json['entity_unique_id'] == null ? undefined : json['entity_unique_id'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
        'href': json['href'] == null ? undefined : json['href'],
        'entity_type': json['entity_type'] == null ? undefined : json['entity_type'],
        'entity_slug': json['entity_slug'] == null ? undefined : json['entity_slug'],
        'routes': json['routes'] == null ? undefined : json['routes'],
    };
}

export function SitemapinterfaceInnerToJSON(json: any): SitemapinterfaceInner {
    return SitemapinterfaceInnerToJSONTyped(json, false);
}

export function SitemapinterfaceInnerToJSONTyped(value?: SitemapinterfaceInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_unique_id': value['entity_unique_id'],
        'updated_at': value['updated_at'],
        'href': value['href'],
        'entity_type': value['entity_type'],
        'entity_slug': value['entity_slug'],
        'routes': value['routes'],
    };
}

